/* MoniKas Gold v2 - gram-first tabungan emas */
(function(){
  'use strict';
  const GAS='https://script.google.com/macros/s/AKfycbz8kXgT4mA_plY2n-g6XVSbqSy57ZVphjdjs4vF8_bo32bWD0YpSqQ0tK3zYB6OmC4_6w/exec';
  const GOLD=new Set(['Ayah','Biyan','Eren','Bunda']);
  let price={sell:2624000,buyback:2477000,date:'02 Sep 2026',source:'ANTAM Logam Mulia'};
  const $=id=>document.getElementById(id);
  const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  const grams=n=>Number(n||0).toLocaleString('id-ID',{minimumFractionDigits:0,maximumFractionDigits:4});
  function jsonp(url){return new Promise((resolve,reject)=>{const cb='mkGoldV2_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const timer=setTimeout(()=>{if(!done){done=true;s.remove();try{delete window[cb]}catch(e){}reject(new Error('timeout'))}},12000);window[cb]=v=>{if(done)return;done=true;clearTimeout(timer);s.remove();try{delete window[cb]}catch(e){}resolve(v)};s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);s.remove();try{delete window[cb]}catch(e){}reject(new Error('network'))};s.src=url+(url.includes('?')?'&':'?')+'callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(s)});}
  function isGold(){return GOLD.has(String($('fund')?.value||'').trim());}
  function ensureUI(){const fund=$('fund');if(!fund||$('goldBoxV2'))return;const wrap=fund.closest('div');const box=document.createElement('div');box.id='goldBoxV2';box.className='hidden';box.style.cssText='margin-top:10px;padding:14px;border:1px solid #f0c36a;border-radius:14px;background:#fffbeb';box.innerHTML='<div style="display:flex;justify-content:space-between;gap:8px"><div><b>🪙 Tabungan Emas</b><div class="hint">Masukkan jumlah dalam gram. Nilai rupiah dihitung otomatis berdasarkan harga buyback ANTAM terbaru.</div></div><span class="pill" style="background:#fef3c7;color:#92400e">GRAM</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px"><div><div class="label" style="margin-bottom:6px">Jumlah Emas (gram)</div><input id="goldGramsV2" class="input" type="number" min="0.0001" step="0.0001" inputmode="decimal" placeholder="0,0000"></div><div><div class="label" style="margin-bottom:6px">Nilai Rupiah</div><input id="goldValueV2" class="input" type="text" readonly placeholder="Otomatis"></div></div><div id="goldPriceV2" class="hint" style="margin-top:8px"></div>';wrap.parentElement.appendChild(box);$('goldGramsV2').addEventListener('input',updateGoldUI);fund.addEventListener('change',toggleGold);toggleGold();}
  function toggleGold(){const gold=isGold(),box=$('goldBoxV2'),amount=$('amount');if(box)box.classList.toggle('hidden',!gold);if(amount){amount.readOnly=gold;amount.placeholder=gold?'Nilai Rupiah (otomatis)':'Nominal (Rp)';}updateGoldUI();}
  function updateGoldUI(){const g=Number($('goldGramsV2')?.value||0),v=g*(Number(price.buyback)||0);if($('goldValueV2'))$('goldValueV2').value=g?rupiah(v):'';if($('amount')&&isGold())$('amount').value=g?Math.round(v):'';if($('goldPriceV2'))$('goldPriceV2').textContent=`Harga buyback ANTAM: ${rupiah(price.buyback)}/gram • Harga jual 1 gram: ${rupiah(price.sell)}/gram${price.date?' • '+price.date:''}`;}
  async function loadPrice(){try{const r=await jsonp(GAS+'?action=getGoldPrice');if(r&&r.ok)price={...price,...r};}catch(e){}updateGoldUI();}
  function patchSubmit(){const form=$('txForm');if(!form||form.__goldV2)return;form.__goldV2=true;form.addEventListener('submit',function(ev){if(!isGold())return;const g=Number($('goldGramsV2')?.value||0);if(!(g>0)){ev.preventDefault();ev.stopImmediatePropagation();alert('Masukkan jumlah emas dalam gram.');return;}const val=Math.round(g*(Number(price.buyback)||0));$('amount').value=String(val);window.__mkGoldDraft={goldGrams:g,goldPrice:Number(price.buyback)||0,goldValue:val,goldValuation:'buyback',goldPriceDate:price.date||'',goldFund:String($('fund').value||'')};},true);}
  function patchFetch(){if(typeof window.fetch!=='function'||window.fetch.__goldV2)return;const original=window.fetch;async function wrapped(input,init){try{const d=window.__mkGoldDraft;if(d&&d.goldFund&&init&&init.body){let b=init.body;if(typeof b==='string'){try{const o=JSON.parse(b);o.goldGrams=d.goldGrams;o.goldPrice=d.goldPrice;o.goldValue=d.goldValue;o.goldValuation=d.goldValuation;o.goldPriceDate=d.goldPriceDate;o.amount=d.goldValue;o.fund=d.goldFund;init={...init,body:JSON.stringify(o)}}catch(e){try{const u=new URLSearchParams(b);u.set('goldGrams',d.goldGrams);u.set('goldPrice',d.goldPrice);u.set('goldValue',d.goldValue);u.set('goldValuation',d.goldValuation);u.set('goldPriceDate',d.goldPriceDate);u.set('amount',d.goldValue);u.set('fund',d.goldFund);init={...init,body:u.toString()}}catch(e2){}}}}}catch(e){}const res=await original.call(this,input,init);window.__mkGoldDraft=null;return res;}wrapped.__goldV2=true;window.fetch=wrapped;}
  async function renderGoldFunds(){try{const r=await jsonp(GAS+'?action=getFunds');if(!r||!r.ok)return;const host=$('funds');if(!host)return;(r.data||[]).filter(f=>GOLD.has(f.name)).forEach(f=>{const card=[...host.querySelectorAll('.fund')].find(c=>c.querySelector('.fund-name')?.textContent.trim()===f.name);if(!card)return;const g=Number(f.goldGrams||0),v=Number(f.goldValue||0),bal=card.querySelector('.fund-bal'),meta=card.querySelector('.fund-meta');if(bal)bal.innerHTML=`${grams(g)} gram<br><span style="font-size:17px">≈ ${rupiah(v)}</span>`;if(meta)meta.textContent=`Saldo emas ${grams(g)} gram • Buyback ${rupiah(price.buyback)}/gram`;});}catch(e){}}
  function addGoldBanner(){const sec=$('funds')?.closest('.card');if(!sec||$('goldBannerV2'))return;const b=document.createElement('div');b.id='goldBannerV2';b.style.cssText='margin-top:12px;padding:12px;background:#fffbeb;border:1px solid #f0c36a;border-radius:13px';b.innerHTML='<b>🪙 Harga Emas Terkini</b><div id="goldBannerTextV2" class="hint" style="margin-top:4px">Mengambil harga...</div>';sec.appendChild(b)}
  function refreshBanner(){if($('goldBannerTextV2'))$('goldBannerTextV2').textContent=`ANTAM buyback ${rupiah(price.buyback)}/gram • harga jual dasar ${rupiah(price.sell)}/gram${price.date?' • '+price.date:''}`;}
  function init(){ensureUI();patchSubmit();patchFetch();addGoldBanner();refreshBanner();updateGoldUI();loadPrice().then(refreshBanner);setTimeout(renderGoldFunds,1000);setTimeout(renderGoldFunds,3000);setInterval(()=>{loadPrice().then(refreshBanner);renderGoldFunds()},60000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
