/* MoniKas Gold v1
 * Tabungan Emas: input gram, calculate current rupiah value from ANTAM buyback price.
 */
(function(){
  'use strict';
  const GAS='https://script.google.com/macros/s/AKfycbz8kXgT4mA_plY2n-g6XVSbqSy57ZVphjdjs4vF8_bo32bWD0YpSqQ0tK3zYB6OmC4_6w/exec';
  const GOLD_FUNDS=new Set(['Ayah','Biyan','Eren','Bunda']);
  let goldPrice={sell:2624000,buyback:2477000,source:'ANTAM Logam Mulia',date:'',updatedAt:''};
  let goldFunds=[];
  const $=id=>document.getElementById(id);
  const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  const grams=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:4});
  function jsonp(url){return new Promise((resolve,reject)=>{const cb='mkGold_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script'),tm=setTimeout(()=>{cleanup();reject(new Error('timeout'))},12000);function cleanup(){clearTimeout(tm);try{delete window[cb]}catch(e){}s.remove()}window[cb]=v=>{cleanup();resolve(v)};s.onerror=()=>{cleanup();reject(new Error('network'))};s.src=url+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(s)})}
  function injectUI(){const fundEl=$('fund');if(!fundEl)return;const box=document.createElement('div');box.id='goldBox';box.className='hidden';box.style.cssText='margin-top:10px;padding:13px;border:1px solid #f0c36a;border-radius:14px;background:#fffbeb';box.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><div><b>🪙 Tabungan Emas</b><div style="font-size:11px;color:#64748b;margin-top:3px">Masukkan gram. Nilai rupiah dihitung otomatis dari harga buyback terbaru ANTAM.</div></div><span style="font-size:11px;padding:5px 8px;border-radius:999px;background:#fef3c7;color:#92400e;font-weight:800">Harga otomatis</span></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:9px"><div><div style="font-size:11px;color:#64748b;margin-bottom:5px">Gram Emas</div><input id="goldGrams" class="input" type="number" min="0.0001" step="0.0001" placeholder="0,00"></div><div><div style="font-size:11px;color:#64748b;margin-bottom:5px">Nilai Rupiah</div><input id="goldValue" class="input" type="text" readonly></div></div><div id="goldPriceInfo" style="font-size:11px;color:#64748b;margin-top:8px">Mengambil harga emas terbaru…</div>`;fundEl.parentElement.appendChild(box);$('goldGrams').addEventListener('input',syncGoldValue)}
  function isGoldFund(){return GOLD_FUNDS.has(($('fund')?.value||'').trim())}
  function showGoldBox(){const box=$('goldBox');if(!box)return;box.classList.toggle('hidden',!isGoldFund());syncGoldValue()}
  function syncGoldValue(){const g=Number($('goldGrams')?.value||0),v=g*Number(goldPrice.buyback||0);if($('goldValue'))$('goldValue').value=g?rupiah(v):'';if($('goldPriceInfo'))$('goldPriceInfo').textContent=`Buyback ANTAM: ${rupiah(goldPrice.buyback)}/gram • Harga jual: ${rupiah(goldPrice.sell)}/gram${goldPrice.date?' • '+goldPrice.date:''}`}
  async function loadGoldPrice(){try{const r=await jsonp(GAS+'?action=getGoldPrice');if(r?.ok){goldPrice=r;syncGoldValue();}}catch(e){syncGoldValue()}}
  async function loadGoldFunds(){try{const r=await jsonp(GAS+'?action=getFunds');if(r?.ok)goldFunds=r.data||[];renderGoldFunds()}catch(e){renderGoldFunds()}}
  function renderGoldFunds(){const host=$('funds');if(!host)return;goldFunds.filter(f=>GOLD_FUNDS.has(f.name)).forEach(f=>{const cards=[...host.querySelectorAll('.fund')],card=cards.find(c=>c.querySelector('.fund-name')?.textContent.trim()===f.name);if(!card)return;const bal=Number(f.goldGrams||0),val=Number(f.goldValue||0),balEl=card.querySelector('.fund-bal'),meta=card.querySelector('.fund-meta');if(balEl)balEl.innerHTML=`${grams(bal)} gram<br><span style="font-size:17px">≈ ${rupiah(val)}</span>`;if(meta)meta.textContent=`Saldo emas ${grams(bal)} gram • Buyback ${rupiah(goldPrice.buyback)}/gram`})}
  function patchPostTx(){if(typeof window.postTx!=='function'||window.postTx.__goldPatched)return;const original=window.postTx;function wrapped(t){if(isGoldFund()){const g=Number($('goldGrams')?.value||0),p=Number(goldPrice.buyback||0),v=g*p;t.goldGrams=g;t.goldPrice=p;t.goldValue=v;t.goldValuation='buyback';t.goldPriceDate=goldPrice.date||'';t.amount=v}return original(t)}wrapped.__goldPatched=true;window.postTx=wrapped}
  function patchNormalizeTx(){if(typeof window.normalizeTx!=='function'||window.normalizeTx.__goldPatched)return;const original=window.normalizeTx;function wrapped(t){const x=original(t);x.goldGrams=Number(t.goldGrams||0);x.goldPrice=Number(t.goldPrice||0);x.goldValue=Number(t.goldValue||0);x.goldValuation=String(t.goldValuation||'');x.goldPriceDate=String(t.goldPriceDate||'');return x}wrapped.__goldPatched=true;window.normalizeTx=wrapped}
  function addGoldSummary(){const section=document.querySelector('#funds')?.closest('.card');if(!section||$('goldSummary'))return;const info=document.createElement('div');info.id='goldSummary';info.style.cssText='margin-top:12px;padding:12px;background:#fffbeb;border:1px solid #f0c36a;border-radius:13px';info.innerHTML='<b>Harga Emas Terkini</b><div id="goldSummaryText" style="font-size:12px;color:#64748b;margin-top:4px">Mengambil harga...</div>';section.appendChild(info)}
  function refreshSummary(){if($('goldSummaryText'))$('goldSummaryText').textContent=`ANTAM buyback ${rupiah(goldPrice.buyback)}/gram • jual ${rupiah(goldPrice.sell)}/gram${goldPrice.date?' • '+goldPrice.date:''}`}
  function init(){injectUI();addGoldSummary();patchPostTx();patchNormalizeTx();$('fund')?.addEventListener('change',showGoldBox);const oldRenderFunds=window.renderFunds;if(typeof oldRenderFunds==='function'&&!oldRenderFunds.__goldWrapped){const wrapped=function(){oldRenderFunds();renderGoldFunds();showGoldBox()};wrapped.__goldWrapped=true;window.renderFunds=wrapped}showGoldBox();refreshSummary();loadGoldPrice().then(refreshSummary);loadGoldFunds();setInterval(()=>{loadGoldPrice().then(()=>{renderGoldFunds();refreshSummary()});loadGoldFunds()},300000);setTimeout(patchPostTx,500);setTimeout(patchNormalizeTx,500);setTimeout(loadGoldFunds,1500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
