const GAS_KEY='monikas_gas_url';
const $s=id=>document.getElementById(id);
const escS=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function gasUrlS(){return localStorage.getItem(GAS_KEY)||''}
function toastS(msg){let t=$s('toast');if(!t){t=document.createElement('div');t.id='toast';t.style='position:fixed;left:50%;bottom:18px;transform:translateX(-50%);background:#0f172a;color:#fff;padding:10px 14px;border-radius:12px;z-index:9999';document.body.appendChild(t)}t.textContent=msg;clearTimeout(window.__sheetToast);window.__sheetToast=setTimeout(()=>t.remove(),2600)}
function setPillS(){const b=$s('sync');if(b)b.textContent=gasUrlS()?'Sheets aktif':'Perangkat'}
async function sendS(payload){const url=gasUrlS();if(!url)return false;try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return true}catch(e){return false}}
function latestTxS(){try{const d=JSON.parse(localStorage.getItem('monikas_v2_local')||'{}');return (d.transactions||[]).sort((a,b)=>Number(b.id)-Number(a.id))[0]}catch{return null}}
async function syncLatestS(){const t=latestTxS();if(!t)return;const p=$s('preview');const img=p?.src?.startsWith('data:image')?p.src:'';const ok=await sendS({action:'saveTransaction',id:t.id,date:t.date,type:t.type,merchant:t.merchant||'',description:t.desc||'',category:t.category||'',amount:Number(t.amount)||0,ocrConfidence:t.receipt?.confidence||'',ocrText:t.receipt?.ocrText||'',receipt:img?{dataUrl:img}:null,source:'MoniKas V2'});toastS(ok?'Rekap masuk Google Sheet':'Transaksi tersimpan lokal; rekap belum terkirim')}
function openSettingsS(){const old=gasUrlS();let m=document.getElementById('sheetSyncModal');if(!m){m=document.createElement('div');m.id='sheetSyncModal';m.style='position:fixed;inset:0;background:#0f172a88;display:grid;place-items:center;padding:16px;z-index:9998';m.innerHTML='<div style="width:min(520px,100%);background:#fff;border-radius:20px;padding:18px"><div style="display:flex;justify-content:space-between"><h3 style="margin:0">Rekap Google Sheet</h3><button id="sxClose">✕</button></div><div style="margin-top:12px"><label style="font-size:12px;color:#64748b">URL Web App Google Apps Script</label><input id="sxUrl" style="width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:12px;margin-top:6px" placeholder="https://script.google.com/macros/s/.../exec"><p style="font-size:12px;color:#64748b;line-height:1.5">Backend <b>apps-script/Code.gs</b> menulis ke spreadsheet yang Anda berikan dan menyimpan foto struk ke folder Google Drive <b>MoniKas Struk</b>.</p></div><div style="display:flex;justify-content:flex-end;gap:8px"><button id="sxCancel">Batal</button><button id="sxSave">Simpan</button></div></div>';document.body.appendChild(m);m.querySelector('#sxClose').onclick=()=>m.remove();m.querySelector('#sxCancel').onclick=()=>m.remove();m.querySelector('#sxSave').onclick=()=>{const v=m.querySelector('#sxUrl').value.trim();if(v)localStorage.setItem(GAS_KEY,v);else localStorage.removeItem(GAS_KEY);m.remove();setPillS();toastS(v?'Rekap Google Sheet aktif':'Rekap dinonaktifkan')}}m.querySelector('#sxUrl').value=old;m.classList.remove('hidden')}
function installSheetSync(){setPillS();const btn=document.createElement('button');btn.id='sheetSyncBtn';btn.textContent='⚙ Rekap';btn.style='border:1px solid #334155;background:#1e293b;color:#fff;border-radius:10px;padding:9px 12px';btn.onclick=openSettingsS;const parent=document.querySelector('.user')||document.querySelector('.head');if(parent&&!document.getElementById('sheetSyncBtn'))parent.appendChild(btn);const form=$s('txForm');if(form&&!form.dataset.sheetHook){form.dataset.sheetHook='1';form.addEventListener('submit',()=>setTimeout(syncLatestS,350));}const oldDel=window.delTx;if(oldDel&&!oldDel.__sheetWrapped){const wrap=function(id){oldDel(id);sendS({action:'deleteTransaction',id})};wrap.__sheetWrapped=true;window.delTx=wrap}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installSheetSync);else installSheetSync();
