/** MoniKas V7 - Google Sheet backend + Tabungan Emas (gram-first) */
const SPREADSHEET_ID='1uF7zUH5boy3VA7abBgWQETccIUp1_lrvYDyeDsrWBlo';
const SHEET_TX='TRANSAKSI',SHEET_SUMMARY='REKAP BULANAN',SHEET_FUNDS='POS PEMASUKAN',DRIVE_FOLDER_NAME='MoniKas Struk',APP_NAME='MoniKas';
const FUNDS=['Bank BNI','Bank Jago','Bank BCA','Bank BSI','Ayah','Biyan','Eren','Bunda','Kas Utama','Lainnya'];
const GOLD_FUNDS=['Ayah','Biyan','Eren','Bunda'];
const FUND_SET=Object.freeze(FUNDS.reduce((o,n)=>(o[n]=true,o),{}));
const HEADERS=['TIMESTAMP','ID TRANSAKSI','TANGGAL','JENIS','TOKO/SUMBER','KETERANGAN','KATEGORI','NOMINAL','METODE BAYAR','OCR CONFIDENCE','OCR TEXT','LINK STRUK','FILE ID','SUMBER','POS DANA','JENIS PEMASUKAN','GRAM EMAS','HARGA EMAS/GRAM','NILAI EMAS','METODE VALUASI','TANGGAL HARGA EMAS'];
const FUND_HEADERS=['ID POS','NAMA POS','SALDO AWAL','TOTAL PEMASUKAN','TOTAL PENGELUARAN','SALDO AKHIR','AKTIF','DIBUAT','SALDO EMAS GRAM','NILAI EMAS SAAT INI'];
const SUMMARY_HEADERS=['BULAN','PENDAPATAN','PENGELUARAN','SALDO','JUMLAH TRANSAKSI','% PENGELUARAN/PENDAPATAN'];
function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=String(p.action||'status');if(a==='getTransactions'||a==='getSummary')return out_(getTransactions(),p.callback);if(a==='getFunds')return out_(getFunds(),p.callback);if(a==='getGoldPrice')return out_(getGoldPrice_(),p.callback);if(a==='setup'||a==='status')return out_(setup(),p.callback);if(a==='saveTransaction')return out_(saveTransaction(normalize_(p)),p.callback);if(a==='deleteTransaction')return out_(deleteTransaction(p),p.callback);return out_({ok:false,error:'Action GET tidak dikenal: '+a},p.callback)}catch(err){return out_({ok:false,error:String(err),stack:err.stack||''})}}
function doPost(e){try{const p=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}'),a=String(p.action||'');if(a==='ping')return out_({ok:true,message:'PING OK',spreadsheetId:SPREADSHEET_ID});if(a==='setup')return out_(setup());if(a==='saveTransaction')return out_(saveTransaction(p));if(a==='deleteTransaction')return out_(deleteTransaction(p));if(a==='getTransactions'||a==='getSummary')return out_(getTransactions());if(a==='getFunds')return out_(getFunds());if(a==='addFund')return out_(addFund(p));if(a==='updateFund')return out_(updateFund(p));if(a==='deleteFund')return out_(deleteFund(p));return out_({ok:false,error:'Action tidak dikenal: '+a})}catch(err){return out_({ok:false,error:String(err),stack:err.stack||''})}}
function setup(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),tx=txSheet_(ss),fs=fundSheet_(ss),sm=summarySheet_(ss);const folder=folder_();ensureHeaders_(tx);seedFunds_(fs);rebuildSummary_(ss);rebuildFunds_(ss);fmt_(tx,fs,sm);SpreadsheetApp.flush();return{ok:true,transactionSheet:tx.getName(),fundsSheet:fs.getName(),summarySheet:sm.getName(),folder:folder.getName()}}
function txSheet_(ss){let s=ss.getSheetByName(SHEET_TX);if(!s)s=ss.insertSheet(SHEET_TX);ensureHeaders_(s);return s}
function ensureHeaders_(s){const cur=s.getLastColumn();if(cur===0){s.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);s.setFrozenRows(1);return}const hs=s.getRange(1,1,1,cur).getValues()[0].map(x=>String(x||'').trim());HEADERS.forEach(h=>{if(hs.indexOf(h)===-1)s.getRange(1,s.getLastColumn()+1).setValue(h)});s.setFrozenRows(1)}
function map_(s){ensureHeaders_(s);const hs=s.getRange(1,1,1,s.getLastColumn()).getValues()[0],m={};hs.forEach((h,i)=>{h=String(h||'').trim();if(h)m[h]=i+1});return m}
function v_(r,m,k){return m[k]?r[m[k]-1]:''} function set_(s,row,m,k,val){if(m[k])s.getRange(row,m[k]).setValue(val)}
function fundSheet_(ss){let s=ss.getSheetByName(SHEET_FUNDS);if(!s)s=ss.insertSheet(SHEET_FUNDS);s.getRange(1,1,1,FUND_HEADERS.length).setValues([FUND_HEADERS]);s.setFrozenRows(1);return s}
function summarySheet_(ss){let s=ss.getSheetByName(SHEET_SUMMARY);if(!s)s=ss.insertSheet(SHEET_SUMMARY);s.getRange(1,1,1,SUMMARY_HEADERS.length).setValues([SUMMARY_HEADERS]);s.setFrozenRows(1);return s}
function seedFunds_(s){const names=s.getLastRow()>1?s.getRange(2,2,s.getLastRow()-1,1).getValues().map(r=>String(r[0]).trim()):[];FUNDS.forEach(f=>{if(names.indexOf(f)<0)s.appendRow(['FUND_'+Date.now()+'_'+Math.floor(Math.random()*9999),f,0,0,0,0,true,new Date(),0,0)})}
function folder_(){const i=DriveApp.getFoldersByName(DRIVE_FOLDER_NAME);return i.hasNext()?i.next():DriveApp.createFolder(DRIVE_FOLDER_NAME)}
function normalize_(p){const f=String(p.fund||p.fundSource||'').trim();return{...p,id:String(p.id||'TX_'+Date.now()),date:String(p.date||today_()),type:String(p.type||'expense').toLowerCase()==='income'?'income':'expense',merchant:String(p.merchant||p.store||''),description:String(p.description||p.desc||''),category:String(p.category||'Lainnya'),amount:Number(p.amount)||0,paymentMethod:String(p.paymentMethod||''),ocrConfidence:String(p.ocrConfidence||''),ocrText:String(p.ocrText||''),source:String(p.source||APP_NAME),fund:FUND_SET[f]?f:'',incomeType:String(p.incomeType||''),goldGrams:Number(p.goldGrams)||0,goldPrice:Number(p.goldPrice)||0,goldValue:Number(p.goldValue)||0,goldValuation:String(p.goldValuation||''),goldPriceDate:String(p.goldPriceDate||''),receipt:p.receipt||null}}
function findRow_(s,id){const m=map_(s),c=m['ID TRANSAKSI'];if(!id||!c||s.getLastRow()<2)return 0;const a=s.getRange(2,c,s.getLastRow()-1,1).getValues();for(let i=0;i<a.length;i++)if(String(a[i][0])===String(id))return i+2;return 0}
function saveTransaction(p){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=txSheet_(ss),m=map_(s),id=String(p.id||'TX_'+Date.now()),old=findRow_(s,id),row=old||s.getLastRow()+1,folder=folder_(),fund=FUND_SET[String(p.fund||'').trim()]?String(p.fund||'').trim():'';const gold=GOLD_FUNDS.indexOf(fund)>=0;let g=gold?Number(p.goldGrams||0):0,pv=gold?Number(p.goldPrice||getGoldPrice_().buyback):0,gv=gold?Math.round(g*pv):0;if(gold&&g<=0)throw new Error('Tabungan Emas wajib diisi dalam gram.');if(gold)p.amount=gv;let link='',fid='',oldData;if(p.receipt&&p.receipt.dataUrl){const z=saveReceipt_(String(p.receipt.dataUrl),String(p.date||today_()),id,folder);link=z.url;fid=z.fileId}else if(old){oldData=s.getRange(old,1,1,s.getLastColumn()).getValues()[0];link=String(v_(oldData,m,'LINK STRUK')||'');fid=String(v_(oldData,m,'FILE ID')||'')}set_(s,row,m,'TIMESTAMP',new Date());set_(s,row,m,'ID TRANSAKSI',id);set_(s,row,m,'TANGGAL',String(p.date||today_()));set_(s,row,m,'JENIS',String(p.type||'expense'));set_(s,row,m,'TOKO/SUMBER',String(p.merchant||''));set_(s,row,m,'KETERANGAN',String(p.description||p.desc||''));set_(s,row,m,'KATEGORI',String(p.category||'Lainnya'));set_(s,row,m,'NOMINAL',Number(p.amount)||0);set_(s,row,m,'METODE BAYAR',String(p.paymentMethod||''));set_(s,row,m,'OCR CONFIDENCE',String(p.ocrConfidence||''));set_(s,row,m,'OCR TEXT',String(p.ocrText||''));set_(s,row,m,'LINK STRUK',link);set_(s,row,m,'FILE ID',fid);set_(s,row,m,'SUMBER',String(p.source||APP_NAME));set_(s,row,m,'POS DANA',fund);set_(s,row,m,'JENIS PEMASUKAN',String(p.incomeType||''));set_(s,row,m,'GRAM EMAS',gold?g:0);set_(s,row,m,'HARGA EMAS/GRAM',gold?pv:0);set_(s,row,m,'NILAI EMAS',gold?gv:0);set_(s,row,m,'METODE VALUASI',gold?'BUYBACK':'');set_(s,row,m,'TANGGAL HARGA EMAS',gold?(p.goldPriceDate||getGoldPrice_().date):'');rebuildSummary_(ss);rebuildFunds_(ss);SpreadsheetApp.flush();return{ok:true,id,updated:!!old,fund,goldGrams:gold?g:0,goldPrice:gold?pv:0,goldValue:gold?gv:0}}finally{lock.releaseLock()}}
function getTransactions(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=ss.getSheetByName(SHEET_TX);if(!s||s.getLastRow()<2)return{ok:true,data:[],count:0,source:'Google Sheet'};const m=map_(s),rows=s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues(),tz=Session.getScriptTimeZone()||'Asia/Jakarta';const fmt=x=>{if(x instanceof Date&&!isNaN(x))return Utilities.formatDate(x,tz,'yyyy-MM-dd');const a=String(x||'').trim().match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(a)return a[1]+'-'+String(a[2]).padStart(2,'0')+'-'+String(a[3]).padStart(2,'0');const b=String(x||'').trim().match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(b){let y=+b[3];if(y<100)y+=2000;return y+'-'+String(b[2]).padStart(2,'0')+'-'+String(b[1]).padStart(2,'0')}return''};const data=rows.map(r=>{const f=String(v_(r,m,'POS DANA')||'').trim();return{id:String(v_(r,m,'ID TRANSAKSI')||''),date:fmt(v_(r,m,'TANGGAL')),type:String(v_(r,m,'JENIS')||'expense').toLowerCase()==='income'?'income':'expense',merchant:String(v_(r,m,'TOKO/SUMBER')||''),description:String(v_(r,m,'KETERANGAN')||''),category:String(v_(r,m,'KATEGORI')||'Lainnya'),amount:Number(v_(r,m,'NOMINAL'))||0,paymentMethod:String(v_(r,m,'METODE BAYAR')||''),ocrConfidence:String(v_(r,m,'OCR CONFIDENCE')||''),ocrText:String(v_(r,m,'OCR TEXT')||''),receiptUrl:String(v_(r,m,'LINK STRUK')||''),source:String(v_(r,m,'SUMBER')||APP_NAME),fund:FUND_SET[f]?f:'',fundSource:FUND_SET[f]?f:'',incomeType:String(v_(r,m,'JENIS PEMASUKAN')||''),goldGrams:Number(v_(r,m,'GRAM EMAS'))||0,goldPrice:Number(v_(r,m,'HARGA EMAS/GRAM'))||0,goldValue:Number(v_(r,m,'NILAI EMAS'))||0,goldValuation:String(v_(r,m,'METODE VALUASI')||''),goldPriceDate:String(v_(r,m,'TANGGAL HARGA EMAS')||''),synced:true}}).filter(x=>x.id&&x.date);return{ok:true,data,count:data.length,source:'Google Sheet',spreadsheetId:SPREADSHEET_ID}}
function rebuildFunds_(ss){const fs=fundSheet_(ss),tx=ss.getSheetByName(SHEET_TX);seedFunds_(fs);const n=fs.getLastRow()-1;if(n<1)return;const fd=fs.getRange(2,1,n,FUND_HEADERS.length).getValues(),m=tx?map_(tx):{},rows=tx&&tx.getLastRow()>1?tx.getRange(2,1,tx.getLastRow()-1,tx.getLastColumn()).getValues():[],tot={};rows.forEach(r=>{const f=String(v_(r,m,'POS DANA')||'').trim();if(!FUND_SET[f])return;tot[f] ||= {income:0,expense:0,grams:0};const typ=String(v_(r,m,'JENIS')||'expense').toLowerCase(),a=Number(v_(r,m,'NOMINAL'))||0,g=Number(v_(r,m,'GRAM EMAS'))||0;if(typ==='income')tot[f].income+=a;else tot[f].expense+=a;if(GOLD_FUNDS.indexOf(f)>=0)tot[f].grams+=typ==='income'?g:-g});const gp=getGoldPrice_().buyback;const out=fd.map(r=>{const f=String(r[1]),t=tot[f]||{income:0,expense:0,grams:0},opening=Number(r[2])||0,g=GOLD_FUNDS.indexOf(f)>=0?t.grams:0;return[r[0],f,opening,t.income,t.expense,opening+t.income-t.expense,r[6]!==false,r[7]||new Date(),g,GOLD_FUNDS.indexOf(f)>=0?g*gp:0]});fs.getRange(2,1,out.length,FUND_HEADERS.length).setValues(out)}
function getFunds(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=fundSheet_(ss);seedFunds_(s);rebuildFunds_(ss);const rows=s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,FUND_HEADERS.length).getValues();return{ok:true,data:rows.filter(r=>String(r[1]).trim()).map(r=>({id:String(r[0]),name:String(r[1]),opening:Number(r[2])||0,income:Number(r[3])||0,expense:Number(r[4])||0,balance:Number(r[5])||0,active:r[6]!==false,goldGrams:Number(r[8])||0,goldValue:Number(r[9])||0})),count:rows.length,source:'Google Sheet'}}
function addFund(p){const name=String(p.name||'').trim();if(!name)return{ok:false,error:'Nama pos kosong'};const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=fundSheet_(ss),names=s.getLastRow()>1?s.getRange(2,2,s.getLastRow()-1,1).getValues().map(r=>String(r[0]).trim().toLowerCase()):[];if(names.indexOf(name.toLowerCase())>=0)return{ok:false,error:'Pos sudah ada'};s.appendRow(['FUND_'+Date.now(),name,Number(p.opening)||0,0,0,Number(p.opening)||0,true,new Date(),0,0]);rebuildFunds_(ss);return{ok:true,name}}
function updateFund(p){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=fundSheet_(ss),id=String(p.id||''),rows=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,1).getValues():[];let r=0;for(let i=0;i<rows.length;i++)if(String(rows[i][0])===id){r=i+2;break}if(!r)return{ok:false,error:'Pos tidak ditemukan'};if(p.name)s.getRange(r,2).setValue(String(p.name).trim());s.getRange(r,7).setValue(p.active!==false);rebuildFunds_(ss);return{ok:true,id}}
function deleteFund(p){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=fundSheet_(ss),id=String(p.id||''),rows=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,2).getValues():[];for(let i=0;i<rows.length;i++)if(String(rows[i][0])===id){if(FUND_SET[String(rows[i][1])])return{ok:false,error:'Pos standar tidak boleh dihapus'};s.getRange(i+2,7).setValue(false);rebuildFunds_(ss);return{ok:true,id}}return{ok:false,error:'Pos tidak ditemukan'}}
function deleteTransaction(p){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),s=ss.getSheetByName(SHEET_TX),r=findRow_(s,String(p.id||''));if(!r)return{ok:true,deleted:false};s.deleteRow(r);rebuildSummary_(ss);rebuildFunds_(ss);return{ok:true,deleted:true,id:String(p.id)}}
function rebuildSummary_(ss){const s=summarySheet_(ss);s.clearContents();s.getRange(1,1,1,SUMMARY_HEADERS.length).setValues([SUMMARY_HEADERS]);const tx=ss.getSheetByName(SHEET_TX);if(!tx||tx.getLastRow()<2)return;const m=map_(tx),rows=tx.getRange(2,1,tx.getLastRow()-1,tx.getLastColumn()).getValues(),agg={};rows.forEach(r=>{const d=parseDate_(v_(r,m,'TANGGAL'));if(!d)return;const k=Utilities.formatDate(d,Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM');agg[k] ||= {i:0,e:0,c:0};const a=Number(v_(r,m,'NOMINAL'))||0;if(String(v_(r,m,'JENIS')).toLowerCase()==='income')agg[k].i+=a;else agg[k].e+=a;agg[k].c++});const out=Object.keys(agg).sort().reverse().map(k=>[k,agg[k].i,agg[k].e,agg[k].i-agg[k].e,agg[k].c,agg[k].i?agg[k].e/agg[k].i:0]);if(out.length)s.getRange(2,1,out.length,6).setValues(out)}
function parseDate_(v){if(v instanceof Date&&!isNaN(v))return v;const s=String(v||'').trim();let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return new Date(y,+m[2]-1,+m[1])}return null}
function saveReceipt_(data,date,id,folder){const m=String(data).match(/^data:(image\/[^;]+);base64,(.+)$/);if(!m)throw new Error('Format foto struk tidak valid');const ext=((m[1].split('/')[1]||'jpg').replace('jpeg','jpg'));const f=folder.createFile(Utilities.newBlob(Utilities.base64Decode(m[2]),m[1],'STRUK_'+date+'_'+id+'.'+ext));return{url:f.getUrl(),fileId:f.getId()}}
function fmt_(tx,fs,sm){[tx,fs,sm].forEach(s=>s.getRange(1,1,1,s.getLastColumn()).setFontWeight('bold').setHorizontalAlignment('center'));const m=map_(tx);if(tx.getMaxRows()>1){if(m['NOMINAL'])tx.getRange(2,m['NOMINAL'],tx.getMaxRows()-1,1).setNumberFormat('#,##0');if(m['GRAM EMAS'])tx.getRange(2,m['GRAM EMAS'],tx.getMaxRows()-1,1).setNumberFormat('0.0000');if(m['HARGA EMAS/GRAM'])tx.getRange(2,m['HARGA EMAS/GRAM'],tx.getMaxRows()-1,1).setNumberFormat('#,##0');if(m['NILAI EMAS'])tx.getRange(2,m['NILAI EMAS'],tx.getMaxRows()-1,1).setNumberFormat('#,##0')}}
function getGoldPrice_(){const props=PropertiesService.getScriptProperties(),key='MONIKAS_GOLD_PRICE',cached=props.getProperty(key);try{const r=UrlFetchApp.fetch('https://www.logammulia.com/id/harga-emas-hari-ini',{muteHttpExceptions:true,followRedirects:true,headers:{'User-Agent':'Mozilla/5.0'}}),h=r.getContentText();let sell=0,buy=0,m=h.match(/1\s*gr[^0-9]{0,250}([0-9][0-9.,]{5,})/i);if(m)sell=money_(m[1]);m=h.match(/buyback[^0-9]{0,250}([0-9][0-9.,]{5,})/i);if(m)buy=money_(m[1]);if(!(sell>0))sell=2624000;if(!(buy>0))buy=2477000;const x={ok:true,source:'ANTAM Logam Mulia',sell,buyback:buy,date:today_(),updatedAt:new Date().toISOString(),url:'https://www.logammulia.com/id/harga-emas-hari-ini'};props.setProperty(key,JSON.stringify(x));return x}catch(e){if(cached)try{return JSON.parse(cached)}catch(z){}return{ok:true,source:'fallback',sell:2624000,buyback:2477000,date:today_(),updatedAt:new Date().toISOString()}}}
function money_(s){return Number(String(s||'').replace(/[^0-9]/g,''))||0}function today_(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Jakarta','yyyy-MM-dd')}function out_(o,cb){if(cb){const s=String(cb).replace(/[^a-zA-Z0-9_$.]/g,'');return ContentService.createTextOutput(s+'('+JSON.stringify(o)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}