/** MoniKas V7 Gold - Google Sheets + Drive Backend
 * Gold accounts use grams as the asset balance and current ANTAM buyback as valuation.
 * Existing cash/bank behavior is preserved.
 */
const SPREADSHEET_ID = '1uF7zUH5boy3VA7abBgWQETccIUp1_lrvYDyeDsrWBlo';
const SHEET_TX = 'TRANSAKSI';
const SHEET_SUMMARY = 'REKAP BULANAN';
const SHEET_FUNDS = 'POS PEMASUKAN';
const DRIVE_FOLDER_NAME = 'MoniKas Struk';
const APP_NAME = 'MoniKas';
const DEFAULT_FUNDS = ['Bank BNI','Bank Jago','Bank BCA','Bank BSI','Ayah','Biyan','Eren','Bunda','Kas Utama','Lainnya'];
const GOLD_FUNDS = Object.freeze({Ayah:true,Biyan:true,Eren:true,Bunda:true});
const FUND_SET = Object.freeze(DEFAULT_FUNDS.reduce((o,n)=>(o[n]=true,o),{}));
const GOLD_PRICE_URL = 'https://www.logammulia.com/id/harga-emas-hari-ini';
const GOLD_BUYBACK_URL = 'https://www.logammulia.com/id/sell/gold';
const HEADERS = ['TIMESTAMP','ID TRANSAKSI','TANGGAL','JENIS','TOKO/SUMBER','KETERANGAN','KATEGORI','NOMINAL','METODE BAYAR','OCR CONFIDENCE','OCR TEXT','LINK STRUK','FILE ID','SUMBER','POS DANA','JENIS PEMASUKAN','GRAM EMAS','HARGA EMAS/GRAM','NILAI EMAS','METODE VALUASI','TANGGAL HARGA EMAS'];
const FUND_HEADERS = ['ID POS','NAMA POS','SALDO AWAL','TOTAL PEMASUKAN','TOTAL PENGELUARAN','SALDO AKHIR','AKTIF','DIBUAT','SALDO EMAS (GRAM)','NILAI EMAS SAAT INI'];
const SUMMARY_HEADERS = ['BULAN','PENDAPATAN','PENGELUARAN','SALDO','JUMLAH TRANSAKSI','% PENGELUARAN/PENDAPATAN'];

function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=String(p.action||'status');if(a==='getTransactions'||a==='getSummary')return responseOrJsonp(getTransactionsFromSheet(),p.callback);if(a==='getFunds')return responseOrJsonp(getFunds(),p.callback);if(a==='getGoldPrice')return responseOrJsonp(getGoldPrice(),p.callback);if(a==='setup')return responseOrJsonp(setupMoniKas(),p.callback);if(a==='saveTransaction')return responseOrJsonp(saveTransaction(normalizePayload_(p)),p.callback);if(a==='deleteTransaction')return responseOrJsonp(deleteTransaction(p),p.callback);if(a==='status')return responseOrJsonp(setupMoniKas(),p.callback);if(a==='test')return responseOrJsonp(saveTransaction({id:'GET_TEST_'+Date.now(),date:today(),type:'expense',merchant:'TEST GET',description:'Tes koneksi Web App',category:'Lainnya',amount:1,paymentMethod:'TEST',source:'GET TEST',fund:'Bank BNI'}),p.callback);return responseOrJsonp({ok:false,error:'Action GET tidak dikenal: '+a},p.callback)}catch(err){return response({ok:false,error:String(err),stack:err.stack||''})}}
function doPost(e){try{const p=JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}'),a=String(p.action||'');if(a==='ping')return response({ok:true,message:'PING OK',spreadsheetId:SPREADSHEET_ID});if(a==='setup')return response(setupMoniKas());if(a==='saveTransaction')return response(saveTransaction(p));if(a==='deleteTransaction')return response(deleteTransaction(p));if(a==='getTransactions'||a==='getSummary')return response(getTransactionsFromSheet());if(a==='getFunds')return response(getFunds());if(a==='getGoldPrice')return response(getGoldPrice());if(a==='addFund')return response(addFund(p));if(a==='updateFund')return response(updateFund(p));if(a==='deleteFund')return response(deleteFund(p));return response({ok:false,error:'Action tidak dikenal: '+a})}catch(err){return response({ok:false,error:String(err),stack:err.stack||''})}}

function setupMoniKas(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),tx=getOrCreateTransactionSheet(ss),summary=getOrCreateSummarySheet(ss),funds=getOrCreateFundsSheet(ss),folder=getOrCreateFolder();ensureTransactionHeaders_(tx);seedDefaultFunds(funds);rebuildSummary(ss);rebuildFunds(ss);formatTransactionSheet(tx);formatSummarySheet(summary);formatFundsSheet(funds);SpreadsheetApp.flush();return{ok:true,spreadsheetId:SPREADSHEET_ID,transactionSheet:tx.getName(),summarySheet:summary.getName(),fundsSheet:funds.getName(),driveFolder:folder.getName(),driveFolderId:folder.getId()}}
function getOrCreateTransactionSheet(ss){let sh=ss.getSheetByName(SHEET_TX);if(!sh)sh=ss.insertSheet(SHEET_TX);ensureTransactionHeaders_(sh);return sh}
function ensureTransactionHeaders_(sh){const cur=sh.getLastColumn(),first=cur?sh.getRange(1,1,1,cur).getValues()[0].map(v=>String(v||'').trim()):[];if(!first.length||first.every(h=>!h))sh.getRange(1,1,1,HEADERS.length).setValues([HEADERS]);else HEADERS.forEach(h=>{if(first.indexOf(h)===-1)sh.getRange(1,sh.getLastColumn()+1).setValue(h)});sh.setFrozenRows(1)}
function headerMap_(sh){ensureTransactionHeaders_(sh);const hs=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(v=>String(v||'').trim()),m={};hs.forEach((h,i)=>{if(h)m[h]=i+1});return m}
function rv_(row,map,name){return map[name]?row[map[name]-1]:''}
function wc_(sh,row,map,name,value){if(map[name])sh.getRange(row,map[name]).setValue(value)}
function findRowById(sh,id){const m=headerMap_(sh),c=m['ID TRANSAKSI'];if(!id||!c||sh.getLastRow()<2)return 0;const v=sh.getRange(2,c,sh.getLastRow()-1,1).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(id))return i+2;return 0}
function normalizePayload_(p){const fr=String(p.fund||p.fundSource||'').trim();return{action:'saveTransaction',id:String(p.id||'TX_'+Date.now()),date:String(p.date||today()),type:String(p.type||'expense').toLowerCase()==='income'?'income':'expense',merchant:String(p.merchant||p.store||''),description:String(p.description||p.desc||''),category:String(p.category||'Lainnya'),amount:Number(p.amount)||0,paymentMethod:String(p.paymentMethod||''),ocrConfidence:String(p.ocrConfidence||''),ocrText:String(p.ocrText||''),source:String(p.source||APP_NAME),fund:FUND_SET[fr]?fr:'',incomeType:String(p.incomeType||''),goldGrams:Number(p.goldGrams)||0,goldPrice:Number(p.goldPrice)||0,goldValue:Number(p.goldValue)||0,goldValuation:String(p.goldValuation||''),goldPriceDate:String(p.goldPriceDate||''),receipt:p.receipt||null}}

function saveTransaction(p){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=getOrCreateTransactionSheet(ss),folder=getOrCreateFolder(),map=headerMap_(sh),id=String(p.id||'TX_'+Date.now()),oldRow=findRowById(sh,id),rawFund=String(p.fund||p.fundSource||'').trim(),fund=FUND_SET[rawFund]?rawFund:'';let receiptUrl='',receiptFileId='';const dataUrl=p.receipt&&p.receipt.dataUrl?String(p.receipt.dataUrl):'';if(dataUrl){const saved=saveReceipt(dataUrl,String(p.date||today()),id,folder);receiptUrl=saved.url;receiptFileId=saved.fileId}else if(oldRow){const old=sh.getRange(oldRow,1,1,sh.getLastColumn()).getValues()[0];receiptUrl=String(rv_(old,map,'LINK STRUK')||'');receiptFileId=String(rv_(old,map,'FILE ID')||'')}const gold=isGoldFund_(fund);let goldGrams=Number(p.goldGrams)||0,goldPrice=Number(p.goldPrice)||0,goldValue=Number(p.goldValue)||0;if(gold){if(!(goldGrams>0))return{ok:false,error:'Untuk pos Tabungan Emas, jumlah gram harus lebih dari 0'};const gp=getGoldPrice();if(!goldPrice)goldPrice=Number(gp.buyback)||0;if(!goldValue)goldValue=goldGrams*goldPrice;p.amount=goldValue;p.goldValuation='buyback';p.goldPriceDate=p.goldPriceDate||gp.date||today();}else{goldGrams=0;goldPrice=0;goldValue=0;p.goldValuation='';p.goldPriceDate=''}const targetRow=oldRow||sh.getLastRow()+1;wc_(sh,targetRow,map,'TIMESTAMP',new Date());wc_(sh,targetRow,map,'ID TRANSAKSI',id);wc_(sh,targetRow,map,'TANGGAL',String(p.date||today()));wc_(sh,targetRow,map,'JENIS',String(p.type||'expense'));wc_(sh,targetRow,map,'TOKO/SUMBER',String(p.merchant||''));wc_(sh,targetRow,map,'KETERANGAN',String(p.description||p.desc||''));wc_(sh,targetRow,map,'KATEGORI',String(p.category||'Lainnya'));wc_(sh,targetRow,map,'NOMINAL',Number(p.amount)||0);wc_(sh,targetRow,map,'METODE BAYAR',String(p.paymentMethod||''));wc_(sh,targetRow,map,'OCR CONFIDENCE',String(p.ocrConfidence||''));wc_(sh,targetRow,map,'OCR TEXT',String(p.ocrText||''));wc_(sh,targetRow,map,'LINK STRUK',receiptUrl);wc_(sh,targetRow,map,'FILE ID',receiptFileId);wc_(sh,targetRow,map,'SUMBER',String(p.source||APP_NAME));wc_(sh,targetRow,map,'POS DANA',fund);wc_(sh,targetRow,map,'JENIS PEMASUKAN',String(p.incomeType||''));wc_(sh,targetRow,map,'GRAM EMAS',goldGrams);wc_(sh,targetRow,map,'HARGA EMAS/GRAM',goldPrice);wc_(sh,targetRow,map,'NILAI EMAS',goldValue);wc_(sh,targetRow,map,'METODE VALUASI',String(p.goldValuation||''));wc_(sh,targetRow,map,'TANGGAL HARGA EMAS',String(p.goldPriceDate||''));rebuildSummary(ss);rebuildFunds(ss);SpreadsheetApp.flush();return{ok:true,id:id,updated:Boolean(oldRow),fund:fund,incomeType:String(p.incomeType||''),goldGrams:goldGrams,goldPrice:goldPrice,goldValue:goldValue,goldValuation:String(p.goldValuation||''),goldPriceDate:String(p.goldPriceDate||''),receiptUrl:receiptUrl,receiptFileId:receiptFileId}}finally{lock.releaseLock()}}
function deleteTransaction(p){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(SHEET_TX);if(!sh)return{ok:true,deleted:false};const id=String(p.id||''),r=findRowById(sh,id);if(!r)return{ok:true,deleted:false};const m=headerMap_(sh),old=sh.getRange(r,1,1,sh.getLastColumn()).getValues()[0],fid=String(rv_(old,m,'FILE ID')||'');if(fid){try{DriveApp.getFileById(fid).setTrashed(true)}catch(e){}}sh.deleteRow(r);rebuildSummary(ss);rebuildFunds(ss);SpreadsheetApp.flush();return{ok:true,deleted:true,id:id}}
function saveReceipt(dataUrl,date,id,folder){const m=String(dataUrl).match(/^data:(image\/[^;]+);base64,(.+)$/);if(!m)throw new Error('Format foto struk tidak valid');const file=folder.createFile(Utilities.newBlob(Utilities.base64Decode(m[2]),m[1],'STRUK_'+String(date).replace(/[^0-9-]/g,'')+'_'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_')+'.'+((m[1].split('/')[1]||'jpg').replace('jpeg','jpg'))));return{url:file.getUrl(),fileId:file.getId(),name:file.getName()}}

function getTransactionsFromSheet(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=ss.getSheetByName(SHEET_TX);if(!sh||sh.getLastRow()<2)return{ok:true,data:[],count:0,source:'Google Sheet'};const m=headerMap_(sh),rows=sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).getValues(),tz=Session.getScriptTimeZone()||'Asia/Makassar',fmt=v=>{if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,tz,'yyyy-MM-dd');const s=String(v||'').trim();if(!s)return'';let q=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(q)return q[1]+'-'+String(q[2]).padStart(2,'0')+'-'+String(q[3]).padStart(2,'0');q=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(q){let y=+q[3];if(y<100)y+=2000;return y+'-'+String(q[2]).padStart(2,'0')+'-'+String(q[1]).padStart(2,'0')}const d=new Date(s);return isNaN(d.getTime())?'':Utilities.formatDate(d,tz,'yyyy-MM-dd')};const data=rows.map(r=>{const f=String(rv_(r,m,'POS DANA')||'').trim();return{id:String(rv_(r,m,'ID TRANSAKSI')||''),date:fmt(rv_(r,m,'TANGGAL')),type:String(rv_(r,m,'JENIS')||'expense').toLowerCase()==='income'?'income':'expense',merchant:String(rv_(r,m,'TOKO/SUMBER')||''),description:String(rv_(r,m,'KETERANGAN')||''),desc:String(rv_(r,m,'KETERANGAN')||''),category:String(rv_(r,m,'KATEGORI')||'Lainnya'),amount:Number(rv_(r,m,'NOMINAL'))||0,paymentMethod:String(rv_(r,m,'METODE BAYAR')||''),ocrConfidence:String(rv_(r,m,'OCR CONFIDENCE')||''),ocrText:String(rv_(r,m,'OCR TEXT')||''),receiptUrl:String(rv_(r,m,'LINK STRUK')||''),receiptFileId:String(rv_(r,m,'FILE ID')||''),source:String(rv_(r,m,'SUMBER')||APP_NAME),fund:FUND_SET[f]?f:'',fundSource:FUND_SET[f]?f:'',incomeType:String(rv_(r,m,'JENIS PEMASUKAN')||''),goldGrams:Number(rv_(r,m,'GRAM EMAS'))||0,goldPrice:Number(rv_(r,m,'HARGA EMAS/GRAM'))||0,goldValue:Number(rv_(r,m,'NILAI EMAS'))||0,goldValuation:String(rv_(r,m,'METODE VALUASI')||''),goldPriceDate:String(rv_(r,m,'TANGGAL HARGA EMAS')||''),synced:true}}).filter(x=>x.id&&x.date);return{ok:true,data:data,count:data.length,source:'Google Sheet',spreadsheetId:SPREADSHEET_ID}}

function getGoldPrice(){const fallback={ok:true,sell:2624000,buyback:2477000,source:'ANTAM Logam Mulia',date:today(),updatedAt:new Date().toISOString()};try{const buy=UrlFetchApp.fetch(GOLD_BUYBACK_URL,{muteHttpExceptions:true,followRedirects:true}).getContentText();let m=buy.match(/Harga Buyback[\s\S]{0,400}?Rp\s*([0-9.,]+)/i);if(!m)m=buy.match(/Harga Buyback[^0-9]{0,200}([0-9][0-9.,]{5,})/i);const bb=m?money_(m[1]):0;const sell=UrlFetchApp.fetch(GOLD_PRICE_URL,{muteHttpExceptions:true,followRedirects:true}).getContentText();m=sell.match(/1\s*gr\s*\|\s*([0-9.,]+)/i);if(!m)m=sell.match(/1\s*gr[\s\S]{0,120}?([0-9]{1,3}(?:[.,][0-9]{3})+)/i);const sp=m?money_(m[1]):0;return{ok:true,sell:sp||fallback.sell,buyback:bb||fallback.buyback,source:'ANTAM Logam Mulia',date:today(),updatedAt:new Date().toISOString()}}catch(e){return fallback}}
function money_(v){return Number(String(v||'').replace(/[^0-9]/g,''))||0}
function isGoldFund_(name){return Boolean(GOLD_FUNDS[name])}

function getOrCreateSummarySheet(ss){let sh=ss.getSheetByName(SHEET_SUMMARY);if(!sh)sh=ss.insertSheet(SHEET_SUMMARY);sh.getRange(1,1,1,SUMMARY_HEADERS.length).setValues([SUMMARY_HEADERS]);sh.setFrozenRows(1);return sh}
function rebuildSummary(ss){const tx=ss.getSheetByName(SHEET_TX),sh=getOrCreateSummarySheet(ss);sh.clearContents();sh.getRange(1,1,1,SUMMARY_HEADERS.length).setValues([SUMMARY_HEADERS]);if(!tx||tx.getLastRow()<2)return;const m=headerMap_(tx),rows=tx.getRange(2,1,tx.getLastRow()-1,tx.getLastColumn()).getValues(),map={};rows.forEach(r=>{const d=parseDateValue(rv_(r,m,'TANGGAL'));if(!d)return;const mon=Utilities.formatDate(d,Session.getScriptTimeZone()||'Asia/Makassar','yyyy-MM');map[mon] ||= {income:0,expense:0,count:0};const a=Number(rv_(r,m,'NOMINAL'))||0;if(String(rv_(r,m,'JENIS')).toLowerCase()==='income')map[mon].income+=a;else map[mon].expense+=a;map[mon].count++});const mons=Object.keys(map).sort().reverse();if(!mons.length)return;const out=mons.map(mon=>{const x=map[mon];return[mon,x.income,x.expense,x.income-x.expense,x.count,x.income?x.expense/x.income:0]});sh.getRange(2,1,out.length,6).setValues(out);sh.getRange(2,2,out.length,3).setNumberFormat('#,##0');sh.getRange(2,6,out.length,1).setNumberFormat('0.00%')}
function parseDateValue(v){if(v instanceof Date&&!isNaN(v.getTime()))return v;const s=String(v||'').trim();if(!s)return null;let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(m)return new Date(+m[1],+m[2]-1,+m[3]);m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return new Date(y,+m[2]-1,+m[1])}const d=new Date(s);return isNaN(d.getTime())?null:d}

function getOrCreateFundsSheet(ss){let sh=ss.getSheetByName(SHEET_FUNDS);if(!sh)sh=ss.insertSheet(SHEET_FUNDS);sh.getRange(1,1,1,FUND_HEADERS.length).setValues([FUND_HEADERS]);sh.setFrozenRows(1);return sh}
function seedDefaultFunds(sh){const vals=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,FUND_HEADERS.length).getValues():[],names=new Set(vals.map(r=>String(r[1]||'').trim()).filter(Boolean));DEFAULT_FUNDS.forEach(n=>{if(!names.has(n))sh.appendRow([newFundId(),n,0,0,0,0,true,new Date(),0,0])})}
function newFundId(){return'FUND_'+Date.now()+'_'+Math.floor(Math.random()*10000)}
function rebuildFunds(ss){const tx=ss.getSheetByName(SHEET_TX),fs=getOrCreateFundsSheet(ss);seedDefaultFunds(fs);const n=fs.getLastRow()-1;if(n<1)return;const fd=fs.getRange(2,1,n,FUND_HEADERS.length).getValues(),tot={};let bb=0;try{bb=getGoldPrice().buyback||0}catch(e){}if(tx&&tx.getLastRow()>1){const m=headerMap_(tx),rows=tx.getRange(2,1,tx.getLastRow()-1,tx.getLastColumn()).getValues();rows.forEach(r=>{const f=String(rv_(r,m,'POS DANA')||'').trim();if(!FUND_SET[f])return;const type=String(rv_(r,m,'JENIS')||'expense').toLowerCase(),amt=Number(rv_(r,m,'NOMINAL'))||0,g=Number(rv_(r,m,'GRAM EMAS'))||0;if(!tot[f])tot[f]={income:0,expense:0,goldIncome:0,goldExpense:0};if(type==='income'){tot[f].income+=amt;if(isGoldFund_(f))tot[f].goldIncome+=g}else{tot[f].expense+=amt;if(isGoldFund_(f))tot[f].goldExpense+=g}})}const out=fd.map(r=>{const name=String(r[1]||''),x=tot[name]||{income:0,expense:0,goldIncome:0,goldExpense:0},opening=Number(r[2])||0,g=isGoldFund_(name)?x.goldIncome-x.goldExpense:0,val=isGoldFund_(name)?g*bb:0;return[r[0],name,opening,x.income,x.expense,opening+x.income-x.expense,r[6]!==false,r[7]||new Date(),g,val]});fs.getRange(2,1,out.length,FUND_HEADERS.length).setValues(out)}
function getFunds(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=getOrCreateFundsSheet(ss);seedDefaultFunds(sh);rebuildFunds(ss);const rows=sh.getLastRow()<2?[]:sh.getRange(2,1,sh.getLastRow()-1,FUND_HEADERS.length).getValues(),data=rows.filter(r=>String(r[1]||'').trim()).map(r=>({id:String(r[0]),name:String(r[1]),opening:Number(r[2])||0,income:Number(r[3])||0,expense:Number(r[4])||0,balance:Number(r[5])||0,active:r[6]!==false,goldGrams:Number(r[8])||0,goldValue:Number(r[9])||0}));return{ok:true,data:data,count:data.length,source:'Google Sheet'}}
function addFund(p){const name=String(p.name||'').trim();if(!name)return{ok:false,error:'Nama pos kosong'};const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=getOrCreateFundsSheet(ss),rows=sh.getLastRow()>1?sh.getRange(2,2,sh.getLastRow()-1,1).getValues():[];if(rows.some(r=>String(r[0]).trim().toLowerCase()===name.toLowerCase()))return{ok:false,error:'Pos sudah ada'};const id=newFundId();sh.appendRow([id,name,Number(p.opening)||0,0,0,Number(p.opening)||0,true,new Date(),0,0]);rebuildFunds(ss);return{ok:true,id:id,name:name,opening:Number(p.opening)||0}}
function updateFund(p){const id=String(p.id||''),name=String(p.name||'').trim();if(!id||!name)return{ok:false,error:'ID/nama pos tidak lengkap'};const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=getOrCreateFundsSheet(ss),row=findFundRow_(sh,id);if(!row)return{ok:false,error:'Pos tidak ditemukan'};sh.getRange(row,2).setValue(name);sh.getRange(row,7).setValue(p.active!==false);rebuildFunds(ss);return{ok:true,id:id,name:name}}
function deleteFund(p){const id=String(p.id||'');if(!id)return{ok:false,error:'ID pos kosong'};const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh=getOrCreateFundsSheet(ss),row=findFundRow_(sh,id);if(!row)return{ok:false,error:'Pos tidak ditemukan'};const name=String(sh.getRange(row,2).getValue()||'');if(FUND_SET[name])return{ok:false,error:'Pos standar tidak boleh dihapus'};sh.getRange(row,7).setValue(false);rebuildFunds(ss);return{ok:true,id:id,active:false}}
function findFundRow_(sh,id){if(sh.getLastRow()<2)return 0;const rows=sh.getRange(2,1,sh.getLastRow()-1,1).getValues();for(let i=0;i<rows.length;i++)if(String(rows[i][0])===id)return i+2;return 0}
function formatTransactionSheet(sh){const m=headerMap_(sh);sh.getRange(1,1,1,sh.getLastColumn()).setFontWeight('bold').setHorizontalAlignment('center');sh.setFrozenRows(1);if(m['NOMINAL'])sh.getRange(2,m['NOMINAL'],Math.max(1,sh.getMaxRows()-1),1).setNumberFormat('#,##0');if(m['GRAM EMAS'])sh.getRange(2,m['GRAM EMAS'],Math.max(1,sh.getMaxRows()-1),1).setNumberFormat('0.0000');if(m['HARGA EMAS/GRAM'])sh.getRange(2,m['HARGA EMAS/GRAM'],Math.max(1,sh.getMaxRows()-1),1).setNumberFormat('#,##0');if(m['NILAI EMAS'])sh.getRange(2,m['NILAI EMAS'],Math.max(1,sh.getMaxRows()-1),1).setNumberFormat('#,##0')}
function formatSummarySheet(sh){sh.getRange(1,1,1,SUMMARY_HEADERS.length).setFontWeight('bold').setHorizontalAlignment('center');sh.setFrozenRows(1)}
function formatFundsSheet(sh){sh.getRange(1,1,1,FUND_HEADERS.length).setFontWeight('bold').setHorizontalAlignment('center');sh.setFrozenRows(1);if(sh.getLastRow()>1){sh.getRange(2,3,sh.getLastRow()-1,4).setNumberFormat('#,##0');sh.getRange(2,9,sh.getLastRow()-1,1).setNumberFormat('0.0000');sh.getRange(2,10,sh.getLastRow()-1,1).setNumberFormat('#,##0')}}
function getOrCreateFolder(){const it=DriveApp.getFoldersByName(DRIVE_FOLDER_NAME);return it.hasNext()?it.next():DriveApp.createFolder(DRIVE_FOLDER_NAME)}
function findFundRow(sh,id){return findFundRow_(sh,id)}
function today(){return Utilities.formatDate(new Date(),Session.getScriptTimeZone()||'Asia/Makassar','yyyy-MM-dd')}
function response(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON)}
function responseOrJsonp(obj,callback){if(callback){const safe=String(callback).replace(/[^a-zA-Z0-9_$.]/g,'');return ContentService.createTextOutput(safe+'('+JSON.stringify(obj)+');').setMimeType(ContentService.MimeType.JAVASCRIPT)}return response(obj)}
